### ISSUE TITLE
Multiple ranger js instances are updating/moving simultaneously

### ISSUE THREAD

**Issue by marionebl** [Palmaswell/ranger#3]
**Given** I press the mouse button on one slider
**when** I move to the next slider without releasing the mouse button
**when** I release the mouse button above a second slider
**then** both sliders are moving simultaneously

This behaviour can be recreated with any number of sliders. Presumably the requestAnimationFrame loop should be cancelled when a given area around is left (mouseleave).

**Comment by Palmaswell** [comment]
Will be taken care off, thanks for the feedback

**Comment by Palmaswell** [comment]
The bug has been fixed and I will close the issue. Thanks Mario for the feedback
